# Generated by Django 5.0.2 on 2024-03-01 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banners',
            options={'verbose_name': 'Banner', 'verbose_name_plural': 'Banner'},
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Kontakt', 'verbose_name_plural': 'Kontakt'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name': 'Commit Users', 'verbose_name_plural': 'Commit Users'},
        ),
        migrations.AlterModelOptions(
            name='testimonialuser',
            options={'verbose_name': 'Commit', 'verbose_name_plural': 'Commit'},
        ),
    ]
