# Generated by Django 5.0.2 on 2024-02-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_about_facebook_link_about_instagram_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekdays',
            name='from_weekday_uz',
            field=models.IntegerField(choices=[(1, 'Dushanba'), (2, 'Seshanba'), (3, 'Chorshanba'), (4, 'Payshanba'), (5, 'Juma'), (6, 'Shanba'), (7, 'Yaxshanba')], verbose_name='Qaysi haftadan'),
        ),
        migrations.AlterField(
            model_name='weekdays',
            name='to_weekday_uz',
            field=models.IntegerField(choices=[(1, 'Dushanba'), (2, 'Seshanba'), (3, 'Chorshanba'), (4, 'Payshanba'), (5, 'Juma'), (6, 'Shanba'), (7, 'Yaxshanba')], verbose_name='Qaysi Haftagacha'),
        ),
        migrations.AlterField(
            model_name='weekends',
            name='week_uz',
            field=models.IntegerField(choices=[(1, 'Dushanba'), (2, 'Seshanba'), (3, 'Chorshanba'), (4, 'Payshanba'), (5, 'Juma'), (6, 'Shanba'), (7, 'Yaxshanba')], verbose_name='Qaysi Hafta Kunni'),
        ),
    ]
