# Generated by Django 5.0.2 on 2024-03-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_banners_options_alter_contacts_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('title_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('short_description_en', models.TextField(blank=True, null=True)),
                ('short_description_uz', models.TextField(blank=True, null=True)),
                ('short_description_ru', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='partners/')),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('partner_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Hamkorlar',
                'verbose_name_plural': 'Hamkorlar',
            },
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.AlterModelOptions(
            name='clinicmember',
            options={'verbose_name': 'Mutaxassislar', 'verbose_name_plural': 'Mutaxassislar'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name': 'Commit', 'verbose_name_plural': 'Commit'},
        ),
        migrations.AlterModelOptions(
            name='testimonialuser',
            options={'verbose_name': 'Commit Users', 'verbose_name_plural': 'Commit Users'},
        ),
    ]
