# Generated by Django 5.0.2 on 2024-02-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_weekdays_from_weekday_uz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicmember',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name="O'zi Xaqida Ma'lumot"),
        ),
        migrations.AlterField(
            model_name='clinicmember',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name="O'zi Xaqida Ma'lumot"),
        ),
        migrations.AlterField(
            model_name='clinicmember',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name="O'zi Xaqida Ma'lumot"),
        ),
        migrations.AlterField(
            model_name='clinicmember',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name="O'zi Xaqida Ma'lumot"),
        ),
        migrations.AlterField(
            model_name='clinicmember',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='clinicmember',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Familiya'),
        ),
        migrations.AlterField(
            model_name='clinicmember',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otasini Ism'),
        ),
    ]
