# Generated by Django 5.0.2 on 2024-02-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_clinicmember_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekdays',
            name='from_weekday_en',
            field=models.IntegerField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], null=True, verbose_name='From which week'),
        ),
        migrations.AlterField(
            model_name='weekdays',
            name='from_weekday_ru',
            field=models.IntegerField(blank=True, choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], null=True, verbose_name='C какой недели'),
        ),
        migrations.AlterField(
            model_name='weekdays',
            name='to_weekday_en',
            field=models.IntegerField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], null=True, verbose_name='Until what week'),
        ),
        migrations.AlterField(
            model_name='weekdays',
            name='to_weekday_ru',
            field=models.IntegerField(blank=True, choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], null=True, verbose_name='До какой недели'),
        ),
        migrations.AlterField(
            model_name='weekends',
            name='week_en',
            field=models.IntegerField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], null=True, verbose_name='What day of the week'),
        ),
        migrations.AlterField(
            model_name='weekends',
            name='week_ru',
            field=models.IntegerField(blank=True, choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], null=True, verbose_name='Какой день недели'),
        ),
    ]
