# Generated by Django 5.0.2 on 2025-03-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_category_options_category_my_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='my_order',
            field=models.IntegerField(),
        ),
    ]
